### ISSUE TITLE
Eigen not detected

### ISSUE THREAD

**Issue by ChemicalXandco** [bartoszek/AUR-alice-vision#2]
I have `eigen` version 3.3.8-3 installed with `pacman` on Manjaro stable and at the end of the cmake process the library versions are shown and Eigen does not have a version listed:
```
-- EIGEN: 
-- CERES: 2.0.0
-- FLANN: 1.9.1 (external)
-- CLP: 1.17.6 (external)
-- COINUTILS: 2.11.4 (external)
-- OSI: 0.108.6 (external)
-- LEMON: 1.3.1 (external)
```
Compilation then fails:
```
/home/user/.cache/yay/alice-vision/src/AliceVision-2.2.0/src/aliceVision/mvsData/imageAlgo.cpp:13:1
0: fatal error: Eigen/Eigen: No such file or directory
   13 | #include <Eigen/Eigen>
      |
```
Any ideas?

**Comment by ChemicalXandco** [comment]
This error goes away when I run `export CPLUS_INCLUDE_PATH=/usr/include/eigen3` before installing.

**Comment by bartoszek** [comment]
Can't see any mention of `CPLUS_INCLUDE_PATH` in alice-vision sources beside this [issue](https://github.com/alicevision/AliceVision/issues/817), was this deprecated in `v2.3.1` ?

**Comment by ChemicalXandco** [comment]
For some reason ever since I have upgraded to `v2.3.1` I am no longer having this issue so I shall close this.

**Comment by bartoszek** [comment]
It looks strange to me, since eigen is clearly detected but `EIGNE_VERSION` is empty... have to take a deeper dive into cmake config.
Edit: Ok, it's fine. Instead of using set of configuration variables new `eigen` uses target files `eigen3Traget.cmake` which is included in `alice-vision` configuration rendering `EIGEN3_{VERSION,INCLUDE_DIR,etc}` obsolete.
